cloud:
  aws:
    sqs:
      endpoint: "http://goaws:4100"
      queues:
        message-queue-2: "${cloud.aws.sqs.endpoint}/100010001000/message-queue-2"
    region:
      static: "us-east-1"

server:
  port: 8082

spring:
  application:
    name: consumer-2

debug: true
